import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const toolDirectory = dirname(fileURLToPath(import.meta.url));
const frontendRoot = resolve(toolDirectory, '../..');
const defaultSchemaPath = resolve(frontendRoot, '../backend/openapi/openapi.json');
const requestedSchemaPath = process.argv[2];
const schemaPath = requestedSchemaPath
  ? resolve(process.cwd(), requestedSchemaPath)
  : defaultSchemaPath;
const outputPath = resolve(
  frontendRoot,
  'libs/shared/contracts/src/generated/openapi-schema.ts',
);

function isRecord(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function assertOpenApiDocument(value) {
  if (
    !isRecord(value) ||
    typeof value.openapi !== 'string' ||
    value.openapi.length === 0 ||
    !isRecord(value.info) ||
    typeof value.info.title !== 'string' ||
    !isRecord(value.paths)
  ) {
    throw new Error('The input is not a valid OpenAPI JSON document.');
  }
}

let source;
try {
  source = await readFile(schemaPath, 'utf8');
} catch (error) {
  const reason = error instanceof Error ? error.message : String(error);
  throw new Error(
    `Cannot read OpenAPI schema at ${schemaPath}. Export FastAPI OpenAPI first. ${reason}`,
  );
}

let document;
try {
  document = JSON.parse(source);
} catch (error) {
  const reason = error instanceof Error ? error.message : String(error);
  throw new Error(`OpenAPI schema is not valid JSON: ${reason}`);
}

assertOpenApiDocument(document);

const generated = [
  '/** This file is generated by tools/openapi/generate.mjs. Do not edit manually. */',
  `export const openApiDocument = ${JSON.stringify(document, null, 2)} as const;`,
  '',
  'export type OpenApiPath = keyof typeof openApiDocument.paths;',
  '',
].join('\n');

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated, 'utf8');
console.info(`Generated OpenAPI contract snapshot: ${outputPath}`);
